[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 1_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config